# Generated by Django 5.1.6 on 2025-03-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_type',
            new_name='type',
        ),
    ]
