# Generated by Django 5.1.6 on 2025-03-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_car_type_carmodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='type',
            new_name='car_type',
        ),
    ]
