# Generated by Django 5.1.6 on 2025-03-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_remove_carmodel_car_type_carmodel_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='type',
            new_name='car_type',
        ),
    ]
